In [1]:
import pandas as pd

data = pd.read_csv('data/movie_dataset_final.csv')
data.describe()

,Year,Oscar_winner,Oscar_nominee,Runtime (min),Metascore,IMDb_rating,IMDb_votes,RT_rating,RT_review,Budget,...,Golden_Bear_winner,Golden_Bear_nominee,Golden_Lion_winner,Golden_Lion_nominee,PCA_winner,PCA_nominee,NYFCC_winner,NYFCC_nominee,OFCS_winner,OFCS_nominee
count,2100.000000,2100.000000,2100.000000,2100.000000,2100.000000,2100.000000,2.100000e+03,2100.000000,2100.000000,2.100000e+03,...,2100.000000,2100.000000,2100.000000,2100.000000,2100.000000,2100.000000,2100.000000,2100.000000,2100.000000,2100.000000
mean,2009.000952,0.010000,0.070000,113.255238,57.273333,6.782952,2.006128e+05,60.713810,166.656667,5.680988e+07,...,0.000952,0.015238,0.002381,0.026190,0.007619,0.014286,0.009524,0.021429,0.010476,0.059524
std,6.056350,0.099522,0.255208,19.353722,18.893209,0.864869,2.000501e+05,25.519127,77.845156,5.588360e+07,...,0.030853,0.122528,0.048748,0.159739,0.086975,0.118694,0.097147,0.144843,0.101840,0.236659
min,1999.000000,0.000000,0.000000,75.000000,0.000000,1.400000,2.714300e+04,0.000000,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2004.000000,0.000000,0.000000,99.000000,45.000000,6.200000,8.522700e+04,40.000000,117.000000,1.700000e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2009.000000,0.000000,0.000000,110.000000,58.000000,6.800000,1.305940e+05,65.000000,161.000000,4.000000e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2014.000000,0.000000,0.000000,124.000000,71.000000,7.400000,2.367292e+05,83.000000,209.250000,8.000000e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2019.000000,1.000000,1.000000,224.000000,100.000000,9.000000,2.191307e+06,100.000000,551.000000,3.790000e+08,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [3]:
import pandas_profiling  

data.profile_report(title='Movie Dataset')

Tab(children=(HTML(value='<div id="overview-content" class="row variable spacing">\n    <div class="row">\n   â€¦